local _, GQ = ...
GQ.Data = GQ.Data or {}

-- GENERATED -- Warlock, ALLIANCE, HORDE, levels 1-9. Nothing else is in this file:
-- no Alliance rows and no level 10 or above, so it can sit next to the
-- hand-made Alliance 1-9 data without either overwriting the other.
--
-- The race filter is the class's own playable races for that faction, not the whole
-- faction: a Horde warrior can be Orc, Undead, Tauren or Troll but never a Blood Elf,
-- so Blood Elf starting quests are gated out. Quests are gated on quest_template.RequiredRaces, and
-- faction-exclusive zones are gated by name -- a vendor standing in Darnassus is
-- not race-restricted, the city is.
--
-- No spec column. Warlocks have no talents before level 10, so one list serves all
-- three specs across this range.
--
-- row = { itemId, slot, minLevel, maxLevel, rank, score }
--   optional: suffix, suffixChance  (random-enchantment items -- score assumes the
--   best roll, and suffixChance is the odds of getting any roll of that suffix)

GQ.Data.warlockEarly1to9Facts = {
    [79]={name="Dwarven Cloth Britches",sourceType="quest_reward",instructions="Reward from the quest “The Boar Hunter” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="The Boar Hunter"},
    [80]={name="Soft Fur-lined Shoes",sourceType="quest_reward",instructions="Reward from the quest “Wolves Across the Border” — pick it over the other choices. In Northshire Valley.",zone="Northshire Valley",questName="Wolves Across the Border"},
    [193]={name="Tattered Cloth Vest",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [194]={name="Tattered Cloth Pants",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [195]={name="Tattered Cloth Boots",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [710]={name="Bracers of the People's Militia",sourceType="quest_reward",instructions="Reward from the quest “Patrolling Westfall” — pick it over the other choices. In Westfall.",zone="Westfall",questName="Patrolling Westfall"},
    [711]={name="Tattered Cloth Gloves",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [719]={name="Rabbit Handler Gloves",sourceType="quest_reward",instructions="Reward from the quest “Dwarven Outfitters” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="Dwarven Outfitters"},
    [792]={name="Knitted Sandals",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [793]={name="Knitted Gloves",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [794]={name="Knitted Pants",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [983]={name="Red Linen Sash",sourceType="quest_reward",instructions="Reward from the quest “Red Linen Goods”. In Elwynn Forest.",zone="Elwynn Forest",questName="Red Linen Goods"},
    [1376]={name="Frayed Cloak",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Often cheapest on the auction house."},
    [1421]={name="Worn Hide Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [1429]={name="Patchwork Cloak",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [1430]={name="Patchwork Gloves",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [1431]={name="Patchwork Pants",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [1433]={name="Patchwork Armor",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [1495]={name="Calico Shoes",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Often cheapest on the auction house."},
    [1497]={name="Calico Cloak",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Often cheapest on the auction house."},
    [1917]={name="Jeweled Dagger",sourceType="world_drop",instructions="Drops from Morgaine the Sly (rare spawn) in Goldshire.",zone="Goldshire",npc="Morgaine the Sly"},
    [2114]={name="Snowy Robe",sourceType="world_drop",instructions="Drops from Starving Winter Wolf in Brewnall Village.",zone="Brewnall Village",npc="Starving Winter Wolf"},
    [2117]={name="Thin Cloth Shoes",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2119]={name="Thin Cloth Gloves",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2120]={name="Thin Cloth Pants",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2121]={name="Thin Cloth Armor",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [2310]={name="Embossed Leather Cloak",sourceType="profession",instructions="Crafted with Leatherworking (requires skill 65).",profession="Leatherworking"},
    [2326]={name="Ivy-weave Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Perfect Stout” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="The Perfect Stout"},
    [2367]={name="Woven Boots",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2369]={name="Woven Gloves",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [2568]={name="Brown Linen Vest",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2569]={name="Linen Boots",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2570]={name="Linen Cloak",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2572]={name="Red Linen Robe",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2580]={name="Reinforced Linen Cape",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [2612]={name="Plain Robe",sourceType="vendor",instructions="Bought from Tor'phan in Orgrimmar.",zone="Orgrimmar",npc="Tor'phan"},
    [2905]={name="Goat Fur Cloak",sourceType="quest_reward",instructions="Reward from the quest “The Perfect Stout” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="The Perfect Stout"},
    [2957]={name="Journeyman's Vest",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Often cheapest on the auction house."},
    [2958]={name="Journeyman's Pants",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Often cheapest on the auction house."},
    [2959]={name="Journeyman's Boots",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [2960]={name="Journeyman's Gloves",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [2971]={name="Spellbinder Boots",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Often cheapest on the auction house."},
    [2972]={name="Spellbinder Gloves",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Often cheapest on the auction house."},
    [3008]={name="Wendigo Fur Cloak",sourceType="world_drop",instructions="Drops from Edan the Howler (rare spawn) in Kharanos.",zone="Kharanos",npc="Edan the Howler"},
    [3224]={name="Silver-lined Bracers",sourceType="world_drop",instructions="Drops from Timber (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Timber"},
    [3270]={name="Flax Vest",sourceType="quest_reward",instructions="Reward from the quest “Night Web's Hollow” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Night Web's Hollow"},
    [3274]={name="Flax Boots",sourceType="quest_reward",instructions="Reward from the quest “Rattling the Rattlecages” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Rattling the Rattlecages"},
    [3275]={name="Flax Gloves",sourceType="quest_reward",instructions="Reward from the quest “The Mindless Ones” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="The Mindless Ones"},
    [3289]={name="Ancestral Boots",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Often cheapest on the auction house."},
    [3290]={name="Ancestral Gloves",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Often cheapest on the auction house."},
    [3291]={name="Ancestral Woollies",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Often cheapest on the auction house."},
    [3322]={name="Wispy Cloak",sourceType="world_drop",instructions="Drops from Lost Soul (rare spawn) in Brill.",zone="Brill",npc="Lost Soul"},
    [3323]={name="Ghostly Bracers",sourceType="world_drop",instructions="Drops from Tormented Spirit (rare spawn) in Eastern Kingdoms.",zone="Eastern Kingdoms",npc="Tormented Spirit"},
    [3328]={name="Spider Web Robe",sourceType="world_drop",instructions="Drops from Vicious Night Web Spider in The Bulwark.",zone="The Bulwark",npc="Vicious Night Web Spider"},
    [3331]={name="Melrache's Cape",sourceType="world_drop",instructions="Drops from Captain Melrache in Scarlet Monastery.",zone="Scarlet Monastery",npc="Captain Melrache"},
    [3363]={name="Frayed Belt",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Often cheapest on the auction house."},
    [3365]={name="Frayed Bracers",sourceType="world_drop",instructions="World drop — drops from 62 creature types around level 1-5. Often cheapest on the auction house."},
    [3370]={name="Patchwork Belt",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [3373]={name="Patchwork Bracers",sourceType="world_drop",instructions="World drop — drops from 236 creature types around level 1-10. Often cheapest on the auction house."},
    [3374]={name="Calico Belt",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Often cheapest on the auction house."},
    [3375]={name="Calico Bracers",sourceType="world_drop",instructions="World drop — drops from 242 creature types around level 9-15. Often cheapest on the auction house."},
    [3442]={name="Apprentice Sash",sourceType="quest_reward",instructions="Reward from the quest “A New Plague”. In Tirisfal Glades.",zone="Tirisfal Glades",questName="A New Plague"},
    [3446]={name="Darkwood Staff",sourceType="quest_reward",instructions="Reward from the quest “The Family Crypt” — pick it over the other choices. In Tirisfal Glades.",zone="Tirisfal Glades",questName="The Family Crypt"},
    [3595]={name="Tattered Cloth Belt",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3596]={name="Tattered Cloth Bracers",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3599]={name="Thin Cloth Belt",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [3600]={name="Thin Cloth Bracers",sourceType="vendor",instructions="Bought from Gamili Frosthide in Kharanos.",zone="Kharanos",npc="Gamili Frosthide"},
    [3602]={name="Knitted Belt",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [3603]={name="Knitted Bracers",sourceType="world_drop",instructions="Drops from Pyrewood Tailor in Pyrewood Village.",zone="Pyrewood Village",npc="Pyrewood Tailor"},
    [3606]={name="Woven Belt",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3607]={name="Woven Bracers",sourceType="vendor",instructions="Bought from Lauren Newcomb in Undercity.",zone="Undercity",npc="Lauren Newcomb"},
    [3641]={name="Journeyman's Bracers",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Often cheapest on the auction house."},
    [3643]={name="Spellbinder Bracers",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Often cheapest on the auction house."},
    [3644]={name="Barbaric Cloth Bracers",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Often cheapest on the auction house."},
    [4261]={name="Solliden's Trousers",sourceType="world_drop",instructions="Drops from Farmer Solliden (rare spawn) in Deathknell.",zone="Deathknell",npc="Farmer Solliden"},
    [4307]={name="Heavy Linen Gloves",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [4308]={name="Green Linen Bracers",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [4309]={name="Handstitched Linen Britches",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [4658]={name="Warrior's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Often cheapest on the auction house."},
    [4662]={name="Journeyman's Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Often cheapest on the auction house."},
    [4663]={name="Journeyman's Belt",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [4665]={name="Burnt Cloak",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Often cheapest on the auction house."},
    [4668]={name="Battle Chain Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [4671]={name="Ancestral Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [4672]={name="Ancestral Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Often cheapest on the auction house."},
    [4674]={name="Tribal Cloak",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [4677]={name="Veteran Cloak",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Often cheapest on the auction house."},
    [4680]={name="Brackwater Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Often cheapest on the auction house."},
    [4683]={name="Spellbinder Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Often cheapest on the auction house."},
    [4684]={name="Spellbinder Belt",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Often cheapest on the auction house."},
    [4687]={name="Barbaric Cloth Belt",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Often cheapest on the auction house."},
    [4772]={name="Warm Cloak",sourceType="world_drop",instructions="Drops from Sister Hatelash (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Sister Hatelash"},
    [4854]={name="Demon Scarred Cloak",sourceType="world_drop",instructions="Drops from Ghost Howl (rare spawn) in Thunder Bluff.",zone="Thunder Bluff",npc="Ghost Howl"},
    [4915]={name="Soft Wool Boots",sourceType="quest_reward",instructions="Reward from the quest “Cutting Teeth” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Cutting Teeth"},
    [4916]={name="Soft Wool Vest",sourceType="quest_reward",instructions="Reward from the quest “Sarkoth” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Sarkoth"},
    [4919]={name="Soft Wool Belt",sourceType="quest_reward",instructions="Reward from the quest “Sting of the Scorpid” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Sting of the Scorpid"},
    [4936]={name="Dirt-trodden Boots",sourceType="quest_reward",instructions="Reward from the quest “From The Wreckage....” — pick it over the other choices. In Durotar.",zone="Durotar",questName="From The Wreckage...."},
    [5069]={name="Fire Wand",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Often cheapest on the auction house."},
    [5071]={name="Shadow Wand",sourceType="world_drop",instructions="World drop — drops from 359 creature types around level 9-15. Often cheapest on the auction house."},
    [5458]={name="Dirtwood Belt",sourceType="quest_reward",instructions="Reward from the quest “Oakenscowl” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Oakenscowl"},
    [5591]={name="Rain-spotted Cape",sourceType="quest_reward",instructions="Reward from the quest “The Enchanted Glade” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="The Enchanted Glade"},
    [5604]={name="Elven Wand",sourceType="quest_reward",instructions="Reward from the quest “Bashal'Aran” — pick it over the other choices. In Darkshore.",zone="Darkshore",questName="Bashal'Aran"},
    [5606]={name="Gardening Gloves",sourceType="quest_reward",instructions="Reward from the quest “Timberling Sprouts” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Timberling Sprouts"},
    [5767]={name="Violet Robes",sourceType="world_drop",instructions="Drops from Frostmane Seer in Kharanos.",zone="Kharanos",npc="Frostmane Seer"},
    [6060]={name="Flax Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Damned” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="The Damned"},
    [6148]={name="Web-covered Boots",sourceType="world_drop",instructions="Drops from Mother Fang (rare spawn) in Northshire Valley.",zone="Northshire Valley",npc="Mother Fang"},
    [6173]={name="Snow Boots",sourceType="quest_reward",instructions="Reward from the quest “A New Threat” — pick it over the other choices. In Coldridge Valley.",zone="Coldridge Valley",questName="A New Threat"},
    [6202]={name="Fingerless Gloves",sourceType="world_drop",instructions="Drops from Thuros Lightfingers (rare spawn) in Elwynn Forest.",zone="Elwynn Forest",npc="Thuros Lightfingers"},
    [6215]={name="Balanced Fighting Stick",sourceType="quest_reward",instructions="Reward from the quest “Wanted:  \"Hogger\"” — pick it over the other choices. In Elwynn Forest.",zone="Elwynn Forest",questName="Wanted:  \"Hogger\""},
    [6238]={name="Brown Linen Robe",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [6239]={name="Red Linen Vest",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [6241]={name="White Linen Robe",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [6266]={name="Disciple's Vest",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Often cheapest on the auction house."},
    [6511]={name="Journeyman's Robe",sourceType="world_drop",instructions="World drop — drops from 401 creature types around level 6-14. Often cheapest on the auction house."},
    [6512]={name="Disciple's Robe",sourceType="world_drop",instructions="World drop — drops from 380 creature types around level 8-14. Often cheapest on the auction house."},
    [6514]={name="Disciple's Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Often cheapest on the auction house."},
    [6515]={name="Disciple's Gloves",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Often cheapest on the auction house."},
    [6713]={name="Ripped Pants",sourceType="quest_reward",instructions="Reward from the quest “Burning Blade Medallion” — pick it over the other choices. In Valley of Trials.",zone="Valley of Trials",questName="Burning Blade Medallion"},
    [7026]={name="Linen Belt",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [7095]={name="Bog Boots",sourceType="world_drop",instructions="Drops from Timberling Mire Beast in Teldrassil.",zone="Teldrassil",npc="Timberling Mire Beast"},
    [7351]={name="Disciple's Boots",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Often cheapest on the auction house."},
    [9603]={name="Gritroot Staff",sourceType="quest_reward",instructions="Reward from the quest “The Relics of Wakening” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="The Relics of Wakening"},
    [9742]={name="Simple Cord",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Often cheapest on the auction house."},
    [9743]={name="Simple Shoes",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Often cheapest on the auction house."},
    [9745]={name="Simple Cape",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Often cheapest on the auction house."},
    [9746]={name="Simple Gloves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Often cheapest on the auction house."},
    [9754]={name="Gypsy Cloak",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Often cheapest on the auction house."},
    [10035]={name="Tuxedo Pants",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [10045]={name="Simple Linen Pants",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [10046]={name="Simple Linen Boots",sourceType="profession",instructions="Crafted with Tailoring (requires skill 1).",profession="Tailoring"},
    [10549]={name="Rancher's Trousers",sourceType="quest_reward",instructions="Reward from the quest “Protecting the Herd” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="Protecting the Herd"},
    [10550]={name="Wooly Mittens",sourceType="quest_reward",instructions="Reward from the quest “Tundra MacGrann's Stolen Stash” — pick it over the other choices. In Dun Morogh.",zone="Dun Morogh",questName="Tundra MacGrann's Stolen Stash"},
    [10553]={name="Foreman Vest",sourceType="world_drop",instructions="Drops from Gibblewilt (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Gibblewilt"},
    [10554]={name="Foreman Pants",sourceType="world_drop",instructions="Drops from Gibblewilt (rare spawn) in Brewnall Village.",zone="Brewnall Village",npc="Gibblewilt"},
    [11187]={name="Stemleaf Bracers",sourceType="quest_reward",instructions="Reward from the quest “The Balance of Nature” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="The Balance of Nature"},
    [11189]={name="Woodland Robes",sourceType="quest_reward",instructions="Reward from the quest “Webwood Egg” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="Webwood Egg"},
    [11190]={name="Viny Gloves",sourceType="quest_reward",instructions="Reward from the quest “The Woodland Protector” — pick it over the other choices. In Shadowglen.",zone="Shadowglen",questName="The Woodland Protector"},
    [11287]={name="Lesser Magic Wand",sourceType="profession",instructions="Crafted with Enchanting (requires skill 1).",profession="Enchanting"},
    [11848]={name="Flax Belt",sourceType="quest_reward",instructions="Reward from the quest “Scavenging Deathknell” — pick it over the other choices. In Deathknell.",zone="Deathknell",questName="Scavenging Deathknell"},
    [14086]={name="Beaded Sandals",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Often cheapest on the auction house."},
    [14087]={name="Beaded Cuffs",sourceType="world_drop",instructions="World drop — drops from 241 creature types around level 5-10. Often cheapest on the auction house."},
    [14089]={name="Beaded Gloves",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Often cheapest on the auction house."},
    [14093]={name="Beaded Cord",sourceType="world_drop",instructions="World drop — drops from 314 creature types around level 5-14. Often cheapest on the auction house."},
    [14095]={name="Native Bands",sourceType="world_drop",instructions="World drop — drops from 416 creature types around level 5-14. Often cheapest on the auction house."},
    [14098]={name="Native Cloak",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 5-14. Often cheapest on the auction house."},
    [14099]={name="Native Sash",sourceType="world_drop",instructions="World drop — drops from 435 creature types around level 6-14. Often cheapest on the auction house."},
    [14102]={name="Native Handwraps",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Often cheapest on the auction house."},
    [14110]={name="Native Sandals",sourceType="world_drop",instructions="World drop — drops from 374 creature types around level 8-14. Often cheapest on the auction house."},
    [14115]={name="Aboriginal Bands",sourceType="world_drop",instructions="World drop — drops from 355 creature types around level 9-15. Often cheapest on the auction house."},
    [15925]={name="Journeyman's Stave",sourceType="world_drop",instructions="World drop — drops from 339 creature types around level 6-14. Often cheapest on the auction house."},
    [15944]={name="Ancestral Orb",sourceType="world_drop",instructions="World drop — drops from 466 creature types around level 6-14. Often cheapest on the auction house."},
    [18957]={name="Brushwood Blade",sourceType="quest_reward",instructions="Reward from the quest “Druid of the Claw” — pick it over the other choices. In Teldrassil.",zone="Teldrassil",questName="Druid of the Claw"},
    [20987]={name="Light Cloth Gloves",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20988]={name="Light Cloth Bracers",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20989]={name="Light Cloth Belt",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [20990]={name="Light Cloth Armor",sourceType="vendor",instructions="Bought from Jainthess Thelryn in The Sunspire.",zone="The Sunspire",npc="Jainthess Thelryn"},
    [22784]={name="Sunwell Orb",sourceType="quest_reward",instructions="Reward from the quest “The Twin Ziggurats” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="The Twin Ziggurats"},
    [22971]={name="Hoodoo Wand",sourceType="quest_reward",instructions="Reward from the quest “Zul'Marosh” — pick it over the other choices. In Eversong Woods.",zone="Eversong Woods",questName="Zul'Marosh"},
    [23323]={name="Crown of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “A Thief's Reward”.",questName="A Thief's Reward"},
    [23324]={name="Mantle of the Fire Festival",sourceType="quest_reward",instructions="Reward from the quest “Wild Fires in the Eastern Kingdoms”.",questName="Wild Fires in the Eastern Kingdoms"},
    [23402]={name="Arcanist's Dagger",sourceType="quest_reward",instructions="Reward from the quest “Windrunner Village” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Windrunner Village"},
    [24109]={name="Thick Ravager Belt",sourceType="quest_reward",instructions="Reward from the quest “Beasts of the Apocalypse!” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="Beasts of the Apocalypse!"},
    [24112]={name="Kurkenstoks",sourceType="quest_reward",instructions="Reward from the quest “The Kurken's Hide” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Kurken's Hide"},
    [24113]={name="Cowlen's Bracers of Kinship",sourceType="quest_reward",instructions="Reward from the quest “A Cry For Help”. In Azuremyst Isle.",zone="Azuremyst Isle",questName="A Cry For Help"},
    [27403]={name="Stillpine Stinger",sourceType="quest_reward",instructions="Reward from the quest “The Prophecy of Akida” — pick it over the other choices. In Azuremyst Isle.",zone="Azuremyst Isle",questName="The Prophecy of Akida"},
    [28144]={name="Troll Handler Gloves",sourceType="quest_reward",instructions="Reward from the quest “Report to Captain Helios” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Report to Captain Helios"},
    [28146]={name="Courier's Wraps",sourceType="quest_reward",instructions="Reward from the quest “Delivery to Tranquillien” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Delivery to Tranquillien"},
    [28151]={name="Arcanist's Wand",sourceType="quest_reward",instructions="Reward from the quest “Windrunner Village” — pick it over the other choices. In Ghostlands.",zone="Ghostlands",questName="Windrunner Village"},
}

GQ.Data.warlockEarly1to9 = {
    {2570,"Back",1,2,1,0.04,faction="Alliance"},
    {1376,"Back",1,2,2,0.03,faction="Alliance"},
    {1429,"Back",1,2,3,0.03,faction="Alliance"},
    {4658,"Back",3,3,1,0.04,faction="Alliance"},
    {4662,"Back",3,3,2,0.04,faction="Alliance"},
    {4665,"Back",3,3,3,0.04,faction="Alliance"},
    {3008,"Back",4,4,1,0.05,faction="Alliance"},
    {4668,"Back",4,4,2,0.05,faction="Alliance"},
    {4671,"Back",4,4,3,0.05,faction="Alliance"},
    {1421,"Back",5,5,1,0.05,faction="Alliance"},
    {2905,"Back",5,5,2,0.05,faction="Alliance"},
    {6514,"Back",5,5,3,0.05,faction="Alliance"},
    {5591,"Back",6,6,1,0.06,faction="Alliance"},
    {9745,"Back",6,6,2,0.06,faction="Alliance"},
    {9754,"Back",6,6,3,0.06,faction="Alliance"},
    {2580,"Back",7,7,1,0.07,faction="Alliance"},
    {3331,"Back",7,7,2,0.07,faction="Alliance"},
    {4677,"Back",7,7,3,0.07,faction="Alliance"},
    {2310,"Back",8,8,1,0.07,faction="Alliance"},
    {4680,"Back",8,8,2,0.07,faction="Alliance"},
    {4683,"Back",8,8,3,0.07,faction="Alliance"},
    {1497,"Back",9,9,1,0.07,faction="Alliance"},
    {2310,"Back",9,9,2,0.07,faction="Alliance"},
    {4680,"Back",9,9,3,0.07,faction="Alliance"},
    {2121,"Chest",1,1,1,0.06,faction="Alliance"},
    {11189,"Chest",1,1,2,0.06,faction="Alliance"},
    {20990,"Chest",1,1,3,0.06,faction="Alliance"},
    {1433,"Chest",2,2,1,0.08,faction="Alliance"},
    {2121,"Chest",2,2,2,0.06,faction="Alliance"},
    {11189,"Chest",2,2,3,0.06,faction="Alliance"},
    {2114,"Chest",3,3,1,0.09,faction="Alliance"},
    {2568,"Chest",3,3,2,0.09,faction="Alliance"},
    {1433,"Chest",3,3,3,0.08,faction="Alliance"},
    {3328,"Chest",4,4,1,0.1,faction="Alliance"},
    {5767,"Chest",4,4,2,0.1,faction="Alliance"},
    {2114,"Chest",4,4,3,0.09,faction="Alliance"},
    {2572,"Chest",5,5,1,0.56,faction="Alliance"},
    {6241,"Chest",5,5,2,0.56,faction="Alliance"},
    {6238,"Chest",5,5,3,0.46,faction="Alliance"},
    {10553,"Chest",6,6,1,1.33,faction="Alliance"},
    {6511,"Chest",6,6,2,1.03,faction="Alliance"},
    {2957,"Chest",6,6,3,0.83,faction="Alliance"},
    {10553,"Chest",7,7,1,1.33,faction="Alliance"},
    {6511,"Chest",7,7,2,1.03,faction="Alliance"},
    {6239,"Chest",7,7,3,0.84,faction="Alliance"},
    {6266,"Chest",8,9,1,1.37,faction="Alliance",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {6512,"Chest",8,9,2,1.37,faction="Alliance",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {10553,"Chest",8,9,3,1.33,faction="Alliance"},
    {80,"Feet",1,3,1,0.04,faction="Alliance"},
    {2117,"Feet",1,3,2,0.04,faction="Alliance"},
    {6173,"Feet",1,3,3,0.04,faction="Alliance"},
    {2959,"Feet",4,4,1,0.07,faction="Alliance"},
    {7095,"Feet",4,4,2,0.07,faction="Alliance"},
    {10046,"Feet",4,4,3,0.07,faction="Alliance"},
    {792,"Feet",5,5,1,0.08,faction="Alliance"},
    {6148,"Feet",5,5,2,0.08,faction="Alliance"},
    {14086,"Feet",5,5,3,0.08,faction="Alliance"},
    {3289,"Feet",6,6,1,0.08,faction="Alliance"},
    {7351,"Feet",6,6,2,0.08,faction="Alliance"},
    {792,"Feet",6,6,3,0.08,faction="Alliance"},
    {24112,"Feet",7,7,1,0.28,faction="Alliance"},
    {9743,"Feet",7,7,2,0.09,faction="Alliance"},
    {3289,"Feet",7,7,3,0.08,faction="Alliance"},
    {24112,"Feet",8,8,1,0.28,faction="Alliance"},
    {2569,"Feet",8,8,2,0.1,faction="Alliance"},
    {14110,"Feet",8,8,3,0.1,faction="Alliance"},
    {24112,"Feet",9,9,1,0.28,faction="Alliance"},
    {2971,"Feet",9,9,2,0.1,faction="Alliance"},
    {2569,"Feet",9,9,3,0.1,faction="Alliance"},
    {719,"Hands",1,1,1,0.04,faction="Alliance"},
    {2119,"Hands",1,1,2,0.04,faction="Alliance"},
    {11190,"Hands",1,1,3,0.04,faction="Alliance"},
    {1430,"Hands",2,3,1,0.05,faction="Alliance"},
    {719,"Hands",2,3,2,0.04,faction="Alliance"},
    {2119,"Hands",2,3,3,0.04,faction="Alliance"},
    {2960,"Hands",4,4,1,0.06,faction="Alliance"},
    {5606,"Hands",4,4,2,0.06,faction="Alliance"},
    {1430,"Hands",4,4,3,0.05,faction="Alliance"},
    {793,"Hands",5,5,1,0.07,faction="Alliance"},
    {4307,"Hands",5,5,2,0.07,faction="Alliance"},
    {14089,"Hands",5,5,3,0.07,faction="Alliance"},
    {6202,"Hands",6,6,1,0.07,faction="Alliance"},
    {6515,"Hands",6,6,2,0.07,faction="Alliance"},
    {793,"Hands",6,6,3,0.07,faction="Alliance"},
    {3290,"Hands",7,7,1,0.08,faction="Alliance"},
    {10550,"Hands",7,7,2,0.08,faction="Alliance"},
    {6202,"Hands",7,7,3,0.07,faction="Alliance"},
    {9746,"Hands",8,8,1,0.09,faction="Alliance"},
    {14102,"Hands",8,8,2,0.09,faction="Alliance"},
    {3290,"Hands",8,8,3,0.08,faction="Alliance"},
    {2972,"Hands",9,9,1,0.1,faction="Alliance"},
    {9746,"Hands",9,9,2,0.09,faction="Alliance"},
    {14102,"Hands",9,9,3,0.09,faction="Alliance"},
    {23323,"Head",1,9,1,0.01,faction="Alliance"},
    {10035,"Legs",1,1,1,0.23,faction="Alliance"},
    {79,"Legs",1,1,2,0.05,faction="Alliance"},
    {2120,"Legs",1,1,3,0.05,faction="Alliance"},
    {10035,"Legs",2,2,1,0.23,faction="Alliance"},
    {10045,"Legs",2,2,2,0.07,faction="Alliance"},
    {79,"Legs",2,2,3,0.05,faction="Alliance"},
    {10035,"Legs",3,4,1,0.23,faction="Alliance"},
    {1431,"Legs",3,4,2,0.07,faction="Alliance"},
    {10045,"Legs",3,4,3,0.07,faction="Alliance"},
    {2958,"Legs",5,5,1,0.45,faction="Alliance"},
    {10035,"Legs",5,5,2,0.23,faction="Alliance"},
    {794,"Legs",5,5,3,0.1,faction="Alliance"},
    {10554,"Legs",6,6,1,0.91,faction="Alliance"},
    {2958,"Legs",6,6,2,0.45,faction="Alliance"},
    {10035,"Legs",6,6,3,0.23,faction="Alliance"},
    {10554,"Legs",7,7,1,0.91,faction="Alliance"},
    {10549,"Legs",7,7,2,0.67,faction="Alliance"},
    {2958,"Legs",7,7,3,0.45,faction="Alliance"},
    {3291,"Legs",8,8,1,1.18,faction="Alliance"},
    {10554,"Legs",8,8,2,0.91,faction="Alliance"},
    {10549,"Legs",8,8,3,0.67,faction="Alliance"},
    {4309,"Legs",9,9,1,1.74,faction="Alliance"},
    {3291,"Legs",9,9,2,1.18,faction="Alliance"},
    {10554,"Legs",9,9,3,0.91,faction="Alliance"},
    {1917,"MainHand",5,7,1,0.2,faction="Alliance"},
    {9603,"MainHand",5,7,2,0.2,faction="Alliance"},
    {18957,"MainHand",5,7,3,0.2,faction="Alliance"},
    {6215,"MainHand",8,9,1,0.4,faction="Alliance"},
    {1917,"MainHand",8,9,2,0.2,faction="Alliance"},
    {9603,"MainHand",8,9,3,0.2,faction="Alliance"},
    {11287,"Ranged",5,6,1,5.67,faction="Alliance"},
    {11287,"Ranged",7,7,1,5.67,faction="Alliance"},
    {5069,"Ranged",7,7,2,4.33,faction="Alliance"},
    {11287,"Ranged",8,8,1,5.67,faction="Alliance"},
    {27403,"Ranged",8,8,2,4.74,faction="Alliance"},
    {5604,"Ranged",8,8,3,4.69,faction="Alliance"},
    {11287,"Ranged",9,9,1,5.67,faction="Alliance"},
    {5071,"Ranged",9,9,2,5.18,faction="Alliance"},
    {27403,"Ranged",9,9,3,4.74,faction="Alliance"},
    {15925,"SecondaryHand",5,6,1,0.2,faction="Alliance"},
    {15944,"SecondaryHand",7,9,1,0.45,faction="Alliance"},
    {15925,"SecondaryHand",7,9,2,0.2,faction="Alliance"},
    {23324,"Shoulder",1,9,1,0.01,faction="Alliance"},
    {3599,"Waist",1,2,1,0.04,faction="Alliance"},
    {20989,"Waist",1,2,2,0.04,faction="Alliance"},
    {3363,"Waist",1,2,3,0.02,faction="Alliance"},
    {3370,"Waist",3,3,1,0.05,faction="Alliance"},
    {3599,"Waist",3,3,2,0.04,faction="Alliance"},
    {20989,"Waist",3,3,3,0.04,faction="Alliance"},
    {983,"Waist",4,4,1,0.05,faction="Alliance"},
    {4663,"Waist",4,4,2,0.05,faction="Alliance"},
    {7026,"Waist",4,4,3,0.05,faction="Alliance"},
    {3602,"Waist",5,6,1,0.06,faction="Alliance"},
    {4672,"Waist",5,6,2,0.06,faction="Alliance"},
    {5458,"Waist",5,6,3,0.06,faction="Alliance"},
    {24109,"Waist",7,7,1,0.52,faction="Alliance"},
    {9742,"Waist",7,7,2,0.07,faction="Alliance"},
    {14099,"Waist",7,7,3,0.07,faction="Alliance"},
    {24109,"Waist",8,8,1,0.52,faction="Alliance"},
    {4684,"Waist",8,8,2,0.08,faction="Alliance"},
    {9742,"Waist",8,8,3,0.07,faction="Alliance"},
    {24109,"Waist",9,9,1,0.52,faction="Alliance"},
    {4687,"Waist",9,9,2,0.08,faction="Alliance"},
    {3374,"Waist",9,9,3,0.08,faction="Alliance"},
    {3365,"Wrist",1,2,1,0.02,faction="Alliance"},
    {3600,"Wrist",1,2,2,0.02,faction="Alliance"},
    {11187,"Wrist",1,2,3,0.02,faction="Alliance"},
    {3323,"Wrist",3,3,1,0.04,faction="Alliance"},
    {3641,"Wrist",3,3,2,0.04,faction="Alliance"},
    {14087,"Wrist",3,3,3,0.04,faction="Alliance"},
    {3323,"Wrist",4,4,1,0.04,faction="Alliance"},
    {3373,"Wrist",4,4,2,0.04,faction="Alliance"},
    {3641,"Wrist",4,4,3,0.04,faction="Alliance"},
    {2326,"Wrist",5,5,1,0.05,faction="Alliance"},
    {3224,"Wrist",5,5,2,0.05,faction="Alliance"},
    {3603,"Wrist",5,5,3,0.05,faction="Alliance"},
    {24113,"Wrist",6,6,1,0.25,faction="Alliance"},
    {14095,"Wrist",6,6,2,0.05,faction="Alliance"},
    {2326,"Wrist",6,6,3,0.05,faction="Alliance"},
    {24113,"Wrist",7,8,1,0.25,faction="Alliance"},
    {3375,"Wrist",7,8,2,0.05,faction="Alliance"},
    {3644,"Wrist",7,8,3,0.05,faction="Alliance"},
    {24113,"Wrist",9,9,1,0.25,faction="Alliance"},
    {710,"Wrist",9,9,2,0.07,faction="Alliance"},
    {3643,"Wrist",9,9,3,0.07,faction="Alliance"},
    {2570,"Back",1,2,1,0.04,faction="Horde"},
    {3322,"Back",1,2,2,0.04,faction="Horde"},
    {1376,"Back",1,2,3,0.03,faction="Horde"},
    {4658,"Back",3,3,1,0.04,faction="Horde"},
    {4662,"Back",3,3,2,0.04,faction="Horde"},
    {4665,"Back",3,3,3,0.04,faction="Horde"},
    {4668,"Back",4,4,1,0.05,faction="Horde"},
    {4671,"Back",4,4,2,0.05,faction="Horde"},
    {4674,"Back",4,4,3,0.05,faction="Horde"},
    {1421,"Back",5,5,1,0.05,faction="Horde"},
    {6514,"Back",5,5,2,0.05,faction="Horde"},
    {14098,"Back",5,5,3,0.05,faction="Horde"},
    {4772,"Back",6,6,1,0.06,faction="Horde"},
    {4854,"Back",6,6,2,0.06,faction="Horde"},
    {9745,"Back",6,6,3,0.06,faction="Horde"},
    {2580,"Back",7,7,1,0.07,faction="Horde"},
    {3331,"Back",7,7,2,0.07,faction="Horde"},
    {4677,"Back",7,7,3,0.07,faction="Horde"},
    {2310,"Back",8,8,1,0.07,faction="Horde"},
    {4680,"Back",8,8,2,0.07,faction="Horde"},
    {4683,"Back",8,8,3,0.07,faction="Horde"},
    {1497,"Back",9,9,1,0.07,faction="Horde"},
    {2310,"Back",9,9,2,0.07,faction="Horde"},
    {4680,"Back",9,9,3,0.07,faction="Horde"},
    {193,"Chest",1,1,1,0.06,faction="Horde"},
    {4916,"Chest",1,1,2,0.06,faction="Horde"},
    {20990,"Chest",1,1,3,0.06,faction="Horde"},
    {1433,"Chest",2,2,1,0.08,faction="Horde"},
    {193,"Chest",2,2,2,0.06,faction="Horde"},
    {3270,"Chest",2,2,3,0.06,faction="Horde"},
    {2114,"Chest",3,3,1,0.09,faction="Horde"},
    {2568,"Chest",3,3,2,0.09,faction="Horde"},
    {2612,"Chest",3,3,3,0.09,faction="Horde"},
    {3328,"Chest",4,4,1,0.1,faction="Horde"},
    {2114,"Chest",4,4,2,0.09,faction="Horde"},
    {2568,"Chest",4,4,3,0.09,faction="Horde"},
    {2572,"Chest",5,5,1,0.56,faction="Horde"},
    {6241,"Chest",5,5,2,0.56,faction="Horde"},
    {6238,"Chest",5,5,3,0.46,faction="Horde"},
    {10553,"Chest",6,6,1,1.33,faction="Horde"},
    {6511,"Chest",6,6,2,1.03,faction="Horde"},
    {2957,"Chest",6,6,3,0.83,faction="Horde"},
    {10553,"Chest",7,7,1,1.33,faction="Horde"},
    {6511,"Chest",7,7,2,1.03,faction="Horde"},
    {6239,"Chest",7,7,3,0.84,faction="Horde"},
    {6266,"Chest",8,9,1,1.37,faction="Horde",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {6512,"Chest",8,9,2,1.37,faction="Horde",suffix="of Shadow Wrath",suffixChance=2.6,suffixId=1840,suffixRange="+4-6 spShadow"},
    {10553,"Chest",8,9,3,1.33,faction="Horde"},
    {195,"Feet",1,2,1,0.04,faction="Horde"},
    {3274,"Feet",1,2,2,0.04,faction="Horde"},
    {4915,"Feet",1,2,3,0.04,faction="Horde"},
    {4936,"Feet",3,3,1,0.06,faction="Horde"},
    {195,"Feet",3,3,2,0.04,faction="Horde"},
    {3274,"Feet",3,3,3,0.04,faction="Horde"},
    {2959,"Feet",4,4,1,0.07,faction="Horde"},
    {10046,"Feet",4,4,2,0.07,faction="Horde"},
    {4936,"Feet",4,4,3,0.06,faction="Horde"},
    {792,"Feet",5,5,1,0.08,faction="Horde"},
    {2367,"Feet",5,5,2,0.08,faction="Horde"},
    {14086,"Feet",5,5,3,0.08,faction="Horde"},
    {3289,"Feet",6,6,1,0.08,faction="Horde"},
    {7351,"Feet",6,6,2,0.08,faction="Horde"},
    {792,"Feet",6,6,3,0.08,faction="Horde"},
    {9743,"Feet",7,7,1,0.09,faction="Horde"},
    {3289,"Feet",7,7,2,0.08,faction="Horde"},
    {7351,"Feet",7,7,3,0.08,faction="Horde"},
    {2569,"Feet",8,8,1,0.1,faction="Horde"},
    {14110,"Feet",8,8,2,0.1,faction="Horde"},
    {1495,"Feet",8,8,3,0.09,faction="Horde"},
    {2971,"Feet",9,9,1,0.1,faction="Horde"},
    {2569,"Feet",9,9,2,0.1,faction="Horde"},
    {14110,"Feet",9,9,3,0.1,faction="Horde"},
    {711,"Hands",1,1,1,0.04,faction="Horde"},
    {3275,"Hands",1,1,2,0.04,faction="Horde"},
    {20987,"Hands",1,1,3,0.04,faction="Horde"},
    {1430,"Hands",2,3,1,0.05,faction="Horde"},
    {711,"Hands",2,3,2,0.04,faction="Horde"},
    {3275,"Hands",2,3,3,0.04,faction="Horde"},
    {2960,"Hands",4,4,1,0.06,faction="Horde"},
    {1430,"Hands",4,4,2,0.05,faction="Horde"},
    {711,"Hands",4,4,3,0.04,faction="Horde"},
    {793,"Hands",5,5,1,0.07,faction="Horde"},
    {2369,"Hands",5,5,2,0.07,faction="Horde"},
    {4307,"Hands",5,5,3,0.07,faction="Horde"},
    {6515,"Hands",6,6,1,0.07,faction="Horde"},
    {793,"Hands",6,6,2,0.07,faction="Horde"},
    {2369,"Hands",6,6,3,0.07,faction="Horde"},
    {3290,"Hands",7,7,1,0.08,faction="Horde"},
    {6515,"Hands",7,7,2,0.07,faction="Horde"},
    {793,"Hands",7,7,3,0.07,faction="Horde"},
    {9746,"Hands",8,8,1,0.09,faction="Horde"},
    {14102,"Hands",8,8,2,0.09,faction="Horde"},
    {3290,"Hands",8,8,3,0.08,faction="Horde"},
    {28144,"Hands",9,9,1,0.88,faction="Horde"},
    {2972,"Hands",9,9,2,0.1,faction="Horde"},
    {9746,"Hands",9,9,3,0.09,faction="Horde"},
    {23323,"Head",1,9,1,0.01,faction="Horde"},
    {10035,"Legs",1,1,1,0.23,faction="Horde"},
    {194,"Legs",1,1,2,0.05,faction="Horde"},
    {6713,"Legs",1,1,3,0.05,faction="Horde"},
    {10035,"Legs",2,2,1,0.23,faction="Horde"},
    {10045,"Legs",2,2,2,0.07,faction="Horde"},
    {194,"Legs",2,2,3,0.05,faction="Horde"},
    {10035,"Legs",3,4,1,0.23,faction="Horde"},
    {4261,"Legs",3,4,2,0.08,faction="Horde"},
    {1431,"Legs",3,4,3,0.07,faction="Horde"},
    {2958,"Legs",5,5,1,0.45,faction="Horde"},
    {10035,"Legs",5,5,2,0.23,faction="Horde"},
    {794,"Legs",5,5,3,0.1,faction="Horde"},
    {10554,"Legs",6,7,1,0.91,faction="Horde"},
    {2958,"Legs",6,7,2,0.45,faction="Horde"},
    {10035,"Legs",6,7,3,0.23,faction="Horde"},
    {3291,"Legs",8,8,1,1.18,faction="Horde"},
    {10554,"Legs",8,8,2,0.91,faction="Horde"},
    {2958,"Legs",8,8,3,0.45,faction="Horde"},
    {4309,"Legs",9,9,1,1.74,faction="Horde"},
    {3291,"Legs",9,9,2,1.18,faction="Horde"},
    {10554,"Legs",9,9,3,0.91,faction="Horde"},
    {1917,"MainHand",5,7,1,0.2,faction="Horde"},
    {3446,"MainHand",8,8,1,0.6,faction="Horde"},
    {1917,"MainHand",8,8,2,0.2,faction="Horde"},
    {3446,"MainHand",9,9,1,0.6,faction="Horde"},
    {23402,"MainHand",9,9,2,0.45,faction="Horde"},
    {1917,"MainHand",9,9,3,0.2,faction="Horde"},
    {11287,"Ranged",5,6,1,5.67,faction="Horde"},
    {11287,"Ranged",7,7,1,5.67,faction="Horde"},
    {5069,"Ranged",7,7,2,4.33,faction="Horde"},
    {11287,"Ranged",8,8,1,5.67,faction="Horde"},
    {5069,"Ranged",8,8,2,4.33,faction="Horde"},
    {22971,"Ranged",8,8,3,4.07,faction="Horde"},
    {11287,"Ranged",9,9,1,5.67,faction="Horde"},
    {28151,"Ranged",9,9,2,5.61,faction="Horde"},
    {5071,"Ranged",9,9,3,5.18,faction="Horde"},
    {22784,"SecondaryHand",1,4,1,1.35,faction="Horde"},
    {22784,"SecondaryHand",5,6,1,1.35,faction="Horde"},
    {15925,"SecondaryHand",5,6,2,0.2,faction="Horde"},
    {22784,"SecondaryHand",7,9,1,1.35,faction="Horde"},
    {15944,"SecondaryHand",7,9,2,0.45,faction="Horde"},
    {15925,"SecondaryHand",7,9,3,0.2,faction="Horde"},
    {23324,"Shoulder",1,9,1,0.01,faction="Horde"},
    {3595,"Waist",1,1,1,0.04,faction="Horde"},
    {4919,"Waist",1,1,2,0.04,faction="Horde"},
    {20989,"Waist",1,1,3,0.04,faction="Horde"},
    {3595,"Waist",2,2,1,0.04,faction="Horde"},
    {4919,"Waist",2,2,2,0.04,faction="Horde"},
    {11848,"Waist",2,2,3,0.04,faction="Horde"},
    {3370,"Waist",3,3,1,0.05,faction="Horde"},
    {3595,"Waist",3,3,2,0.04,faction="Horde"},
    {4919,"Waist",3,3,3,0.04,faction="Horde"},
    {4663,"Waist",4,4,1,0.05,faction="Horde"},
    {7026,"Waist",4,4,2,0.05,faction="Horde"},
    {14093,"Waist",4,4,3,0.05,faction="Horde"},
    {3602,"Waist",5,6,1,0.06,faction="Horde"},
    {3606,"Waist",5,6,2,0.06,faction="Horde"},
    {4672,"Waist",5,6,3,0.06,faction="Horde"},
    {3442,"Waist",7,7,1,0.07,faction="Horde"},
    {9742,"Waist",7,7,2,0.07,faction="Horde"},
    {14099,"Waist",7,7,3,0.07,faction="Horde"},
    {4684,"Waist",8,8,1,0.08,faction="Horde"},
    {3442,"Waist",8,8,2,0.07,faction="Horde"},
    {9742,"Waist",8,8,3,0.07,faction="Horde"},
    {4687,"Waist",9,9,1,0.08,faction="Horde"},
    {3374,"Waist",9,9,2,0.08,faction="Horde"},
    {4684,"Waist",9,9,3,0.08,faction="Horde"},
    {3365,"Wrist",1,1,1,0.02,faction="Horde"},
    {3596,"Wrist",1,1,2,0.02,faction="Horde"},
    {20988,"Wrist",1,1,3,0.02,faction="Horde"},
    {3365,"Wrist",2,2,1,0.02,faction="Horde"},
    {3596,"Wrist",2,2,2,0.02,faction="Horde"},
    {6060,"Wrist",2,2,3,0.02,faction="Horde"},
    {3323,"Wrist",3,3,1,0.04,faction="Horde"},
    {3641,"Wrist",3,3,2,0.04,faction="Horde"},
    {14087,"Wrist",3,3,3,0.04,faction="Horde"},
    {3323,"Wrist",4,4,1,0.04,faction="Horde"},
    {3373,"Wrist",4,4,2,0.04,faction="Horde"},
    {3641,"Wrist",4,4,3,0.04,faction="Horde"},
    {3224,"Wrist",5,5,1,0.05,faction="Horde"},
    {3603,"Wrist",5,5,2,0.05,faction="Horde"},
    {3607,"Wrist",5,5,3,0.05,faction="Horde"},
    {14095,"Wrist",6,6,1,0.05,faction="Horde"},
    {3224,"Wrist",6,6,2,0.05,faction="Horde"},
    {3603,"Wrist",6,6,3,0.05,faction="Horde"},
    {3375,"Wrist",7,8,1,0.05,faction="Horde"},
    {3644,"Wrist",7,8,2,0.05,faction="Horde"},
    {4308,"Wrist",7,8,3,0.05,faction="Horde"},
    {28146,"Wrist",9,9,1,0.5,faction="Horde"},
    {3643,"Wrist",9,9,2,0.07,faction="Horde"},
    {14115,"Wrist",9,9,3,0.07,faction="Horde"},
}
